import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import process from 'node:process';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const specPath = resolve(root, 'docs/openapi/openapi.json');
const typesPath = resolve(root, 'frontend/packages/types/src/generated/openapi.d.ts');
const outputArgument = `-Dopenapi.output=${specPath}`;
const command = process.argv[2] ?? '--generate';

if (command === '--sync') {
  await exportOpenApi();
}

if (!['--sync', '--generate', '--check'].includes(command)) {
  throw new Error(`Unknown command: ${command}`);
}

const spec = JSON.parse(await readFile(specPath, 'utf8'));
const generated = await renderTypes(spec);

if (command === '--check') {
  const existing = await readFile(typesPath, 'utf8').catch(() => '');
  if (existing !== generated) {
    process.stderr.write(
      'Generated OpenAPI types are out of date. Run "npm run api:generate".\n'
    );
    process.exitCode = 1;
  }
} else {
  await mkdir(dirname(typesPath), { recursive: true });
  await writeFile(typesPath, generated, 'utf8');
  process.stdout.write(`Generated ${typesPath}\n`);
}

async function exportOpenApi() {
  await mkdir(dirname(specPath), { recursive: true });
  const executable = process.platform === 'win32' ? 'mvn.cmd' : 'mvn';
  const args = [
    '-s',
    '.mvn/mindora-settings.xml',
    '-gs',
    '.mvn/mindora-settings.xml',
    '-pl',
    'mindora-app',
    '-am',
    '-Dtest=OpenApiContractTest',
    '-Dsurefire.failIfNoSpecifiedTests=false',
    outputArgument,
    'test'
  ];

  await new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(executable, args, {
      cwd: resolve(root, 'backend'),
      stdio: 'inherit',
      shell: process.platform === 'win32'
    });
    child.on('error', rejectPromise);
    child.on('exit', (code) => {
      if (code === 0) {
        resolvePromise();
      } else {
        rejectPromise(new Error(`Maven OpenAPI export failed with exit code ${code}.`));
      }
    });
  });

  process.stdout.write(`Exported ${specPath}\n`);
}

async function renderTypes(spec) {
  const ast = await openapiTS(spec);
  return [
    '// This file is generated by "npm run api:generate". Do not edit it manually.',
    '',
    astToString(ast)
  ].join('\n');
}
